test: When kdc fails to start, show the log
This is an attempt to find out why the GitHub Actions OS X build is
failing.

diff --git a/tests/gss/check-context.in b/tests/gss/check-context.in
--- a/tests/gss/check-context.in
+++ b/tests/gss/check-context.in
@@ -115,7 +115,7 @@ ${kadmin} check ${R} || exit 1
 echo u1 > ${objdir}/foopassword
 
 echo Starting kdc
-${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+${kdc} --detach --testing || { echo "kdc failed to start"; cat messages.log; exit 1; }
 kdcpid=`getpid kdc`
 
 trap "kill ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
diff --git a/tests/gss/check-ntlm.in b/tests/gss/check-ntlm.in
--- a/tests/gss/check-ntlm.in
+++ b/tests/gss/check-ntlm.in
@@ -107,7 +107,7 @@ echo u1 > ${objdir}/foopassword
 echo ds > ${objdir}/barpassword
 
 echo Starting kdc
-${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+${kdc} --detach --testing || { echo "kdc failed to start"; cat messages.log; exit 1; }
 kdcpid=`getpid kdc`
 
 trap "kill ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
diff --git a/tests/kdc/check-kdc.in b/tests/kdc/check-kdc.in
--- a/tests/kdc/check-kdc.in
+++ b/tests/kdc/check-kdc.in
@@ -369,7 +369,7 @@ echo notfoo > ${objdir}/notfoopassword
 echo Starting kdc ; > messages.log
 env MallocStackLogging=1 MallocStackLoggingNoCompact=1 MallocErrorAbort=1 MallocLogFile=${objdir}/malloc-log \
 ${kdc} --detach --testing ||
-    { echo "kdc failed to start"; exit 1; }
+    { echo "kdc failed to start"; cat messages.log; exit 1; }
 kdcpid=`getpid kdc`
 
 echo Starting kpasswdd; > messages.log
