Use --detach in tests to avoid waiting

diff --git a/tests/gss/check-basic.in b/tests/gss/check-basic.in
--- a/tests/gss/check-basic.in
+++ b/tests/gss/check-basic.in
@@ -94,14 +94,8 @@ echo "Doing database check"
 ${kadmin} check ${R} || exit 1
 
 echo Starting kdc
-${kdc} &
-kdcpid=$!
-
-sh ${srcdir}/../kdc/wait-kdc.sh
-if [ "$?" != 0 ] ; then
-    kill ${kdcpid}
-    exit 1
-fi
+${kdc} --testing --detach || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
 
diff --git a/tests/gss/check-ntlm.in b/tests/gss/check-ntlm.in
--- a/tests/gss/check-ntlm.in
+++ b/tests/gss/check-ntlm.in
@@ -106,14 +106,8 @@ echo u1 > ${objdir}/foopassword
 echo ds > ${objdir}/barpassword
 
 echo Starting kdc
-${kdc} &
-kdcpid=$!
-
-sh ${srcdir}/../kdc/wait-kdc.sh
-if [ "$?" != 0 ] ; then
-    kill ${kdcpid}
-    exit 1
-fi
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
 
diff --git a/tests/java/check-kinit.in b/tests/java/check-kinit.in
--- a/tests/java/check-kinit.in
+++ b/tests/java/check-kinit.in
@@ -35,8 +35,11 @@
 #
 
 srcdir="@srcdir@"
+env_setup="@env_setup@"
 objdir="@objdir@"
 port="@port@"
+
+. ${env_setup}
 
 # Disable test if: no data, no java, or socket wrapper
 ../db/have-db || exit 77
@@ -87,14 +90,8 @@ ${kadmin} add -p kaka --use-defaults ${server}@${R} || exit 1
 ${kadmin} ext -k ${keytab} ${server}@${R} || exit 1
 
 echo Starting kdc
-${kdc} &
-kdcpid=$!
-
-sh ${srcdir}/../kdc/wait-kdc.sh
-if [ "$?" != 0 ] ; then
-    kill ${kdcpid}
-    exit 1
-fi
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill -9 ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
 
diff --git a/tests/kdc/check-iprop.in b/tests/kdc/check-iprop.in
--- a/tests/kdc/check-iprop.in
+++ b/tests/kdc/check-iprop.in
@@ -128,23 +128,22 @@ ipropd_slave="${ipropd_slave} --status-file=iprop-slave-status"
 trap "echo 'killing ipropd s + m + kdc'; kill -9 \${ipdm} \${ipds} \${kdcpid} >/dev/null 2>/dev/null; tail messages.log ; tail iprop-stats; exit 1;" EXIT
 
 echo Starting kdc ; > messages.log
-${kdc} &
-kdcpid=$!
-
-sh ${wait_kdc} || exit 1
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 echo "starting master" ; > messages.log
 env ${HEIM_MALLOC_DEBUG} \
 ${ipropd_master} --hostname=localhost -k ${keytab} \
-    --database=${objdir}/current-db &
-ipdm=$!
-sh ${wait_kdc} ipropd-master || exit 1
+    --database=${objdir}/current-db --detach ||
+    { echo "ipropd-master failed to start"; exit 1; }
+ipdm=`getpid ipropd-master`
 
 echo "starting slave" ; > messages.log
 env ${HEIM_MALLOC_DEBUG} \
 KRB5_CONFIG="${objdir}/krb5-slave.conf" \
-${ipropd_slave} --hostname=slave.test.h5l.se -k ${keytab} localhost &
-ipds=$!
+${ipropd_slave} --hostname=slave.test.h5l.se -k ${keytab} --detach localhost ||
+    { echo "ipropd-slave failed to start"; exit 1; }
+ipds=`getpid ipropd-slave`
 sh ${wait_kdc} ipropd-slave messages.log 'slave status change: up-to-date' || exit 1
 sleep 1
 
@@ -213,6 +212,7 @@ echo "kill slave and remove log and database"
 sh ${leaks_kill} ipropd-slave $ipds || exit 1
 rm -f iprop-slave-status
 
+sleep 2
 ${EGREP} 'iprop/slave.test.h5l.se@TEST.H5L.SE.*Down' iprop-stats >/dev/null || exit 1
 
 # ----------------- checking: slave is missing changes while down
@@ -232,8 +232,9 @@ echo "starting slave again" ; > messages.log
 > iprop-stats
 env ${HEIM_MALLOC_DEBUG} \
 KRB5_CONFIG="${objdir}/krb5-slave.conf" \
-${ipropd_slave} --hostname=slave.test.h5l.se -k ${keytab} localhost &
-ipds=$!
+${ipropd_slave} --hostname=slave.test.h5l.se -k ${keytab} --detach localhost ||
+    { echo "ipropd-slave failed to start"; exit 1; }
+ipds=`getpid ipropd-slave`
 sh ${wait_kdc} ipropd-slave messages.log 'slave status change: up-to-date' || exit 1
 sleep 1
 
@@ -259,8 +260,9 @@ rm -f iprop-slave-status
 echo "starting slave" ; > messages.log
 env ${HEIM_MALLOC_DEBUG} \
 KRB5_CONFIG="${objdir}/krb5-slave.conf" \
-${ipropd_slave} --hostname=slave.test.h5l.se -k ${keytab} localhost &
-ipds=$!
+${ipropd_slave} --hostname=slave.test.h5l.se -k ${keytab} --detach localhost ||
+    { echo "ipropd-slave failed to start"; exit 1; }
+ipds=`getpid ipropd-slave`
 sh ${wait_kdc} ipropd-slave messages.log 'slave status change: up-to-date' || exit 1
 sleep 1
 
@@ -304,15 +306,16 @@ cp ${objdir}/current.log.tmp ${objdir}/current.log
 echo "starting master"  ; > messages.log
 env ${HEIM_MALLOC_DEBUG} \
 ${ipropd_master} --hostname=localhost -k ${keytab} \
-    --database=${objdir}/current-db &
-ipdm=$!
-sh ${wait_kdc} ipropd-master || exit 1
+    --database=${objdir}/current-db --detach ||
+    { echo "ipropd-master failed to start"; exit 1; }
+ipdm=`getpid ipropd-master`
 
 echo "starting slave" ; > messages.log
 env ${HEIM_MALLOC_DEBUG} \
 KRB5_CONFIG="${objdir}/krb5-slave.conf" \
-${ipropd_slave} --hostname=slave.test.h5l.se -k ${keytab} localhost &
-ipds=$!
+${ipropd_slave} --hostname=slave.test.h5l.se -k ${keytab} --detach localhost ||
+    { echo "ipropd-slave failed to start"; exit 1; }
+ipds=`getpid ipropd-slave`
 sh ${wait_kdc} ipropd-slave messages.log 'slave status change: up-to-date' || exit 1
 sleep 1
 
@@ -346,9 +349,9 @@ kill -0 ${ipds}  || { echo "slave no longer there"; exit 1; }
 echo "Staring master again" ; > messages.log
 env ${HEIM_MALLOC_DEBUG} \
 ${ipropd_master} --hostname=localhost -k ${keytab} \
-    --database=${objdir}/current-db &
-ipdm=$!
-sh ${wait_kdc} ipropd-master || exit 1
+    --database=${objdir}/current-db --detach ||
+    { echo "ipropd-master failed to start"; exit 1; }
+ipdm=`getpid ipropd-master`
 
 echo "probing for slave pid"
 kill -0 ${ipds}  || { echo "slave no longer there"; exit 1; }
diff --git a/tests/kdc/check-kadmin.in b/tests/kdc/check-kadmin.in
--- a/tests/kdc/check-kadmin.in
+++ b/tests/kdc/check-kadmin.in
@@ -89,15 +89,8 @@ ${kadmin} -l modify --pkinit-acl="CN=baz,DC=test,DC=h5l,DC=se" pkinit@${R} || ex
 echo foo > ${objdir}/foopassword
 
 echo Starting kdc ; > messages.log
-${kdc} &
-kdcpid=$!
-
-sh ${wait_kdc}
-if [ "$?" != 0 ] ; then
-    kill -9 ${kdcpid}
-    kill -9 ${kadmpid}
-    exit 1
-fi
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill -9 ${kdcpid} ${kadmpid}" EXIT
 
diff --git a/tests/kdc/check-referral.in b/tests/kdc/check-referral.in
--- a/tests/kdc/check-referral.in
+++ b/tests/kdc/check-referral.in
@@ -59,7 +59,6 @@ klist="${klist} -c $cache"
 kgetcred="${kgetcred} -c $cache"
 kdestroy="${kdestroy} -c $cache ${afs_no_unlog}"
 
-
 KRB5_CONFIG="${objdir}/krb5.conf"
 export KRB5_CONFIG
 
@@ -101,14 +100,8 @@ ${kadmin} check ${R2} || exit 1
 echo foo > ${objdir}/foopassword
 
 echo Starting kdc ; > messages.log
-${kdc} &
-kdcpid=$!
-
-sh ${wait_kdc}
-if [ "$?" != 0 ] ; then
-    kill -9 ${kdcpid}
-    exit 1
-fi
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill -9 ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
 
diff --git a/tests/ldap/check-ldap.in b/tests/ldap/check-ldap.in
--- a/tests/ldap/check-ldap.in
+++ b/tests/ldap/check-ldap.in
@@ -114,15 +114,8 @@ ${kadmin} list '*' > /dev/null || exit 1
 echo foo > ${objdir}/foopassword
 
 echo Starting kdc
-${kdc} &
-kdcpid=$!
-
-sh ${srcdir}/../kdc/wait-kdc.sh
-if [ "$?" != 0 ] ; then
-    kill ${kdcpid}
-    sh ${srcdir}/slapd-stop
-    exit 1
-fi
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill ${kdcpid}; echo signal killing kdc; sh ${srcdir}/slapd-stop ; exit 1;" EXIT
 
