Use --detach in tests to avoid waiting

diff --git a/tests/gss/check-context.in b/tests/gss/check-context.in
--- a/tests/gss/check-context.in
+++ b/tests/gss/check-context.in
@@ -114,14 +114,8 @@ ${kadmin} check ${R} || exit 1
 echo u1 > ${objdir}/foopassword
 
 echo Starting kdc
-${kdc} &
-kdcpid=$!
-
-sh ${srcdir}/../kdc/wait-kdc.sh
-if [ "$?" != 0 ] ; then
-    kill ${kdcpid}
-    exit 1
-fi
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
 
diff --git a/tests/kdc/check-digest.in b/tests/kdc/check-digest.in
--- a/tests/kdc/check-digest.in
+++ b/tests/kdc/check-digest.in
@@ -94,14 +94,9 @@ ${kadmin} check ${R} || exit 1
 echo $password > ${objdir}/foopassword
 
 echo "Starting kdc" ; > messages.log
-env ${HEIM_MALLOC_DEBUG} ${kdc} &
-kdcpid=$!
-
-sh ${wait_kdc}
-if [ "$?" != 0 ] ; then
-    kill -9 ${kdcpid}
-    exit 1
-fi
+env ${HEIM_MALLOC_DEBUG} ${kdc} --detach --testing ||
+    { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill -9 ${kdcpid}; echo signal killing kdc; cat messages.log; exit 1;" EXIT
 
diff --git a/tests/kdc/check-fast.in b/tests/kdc/check-fast.in
--- a/tests/kdc/check-fast.in
+++ b/tests/kdc/check-fast.in
@@ -88,14 +88,8 @@ echo bar > ${objdir}/barpassword
 
 echo Starting kdc ; > messages.log
 env MallocStackLogging=1 MallocStackLoggingNoCompact=1 MallocErrorAbort=1 MallocLogFile=${objdir}/malloc-log \
-${kdc} &
-kdcpid=$!
-
-sh ${wait_kdc}
-if [ "$?" != 0 ] ; then
-    kill -9 ${kdcpid}
-    exit 1
-fi
+${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 trap "kill -9 ${kdcpid}; echo signal killing kdc; cat messages.log; exit 1;" EXIT
 
diff --git a/tests/kdc/check-kdc.in b/tests/kdc/check-kdc.in
--- a/tests/kdc/check-kdc.in
+++ b/tests/kdc/check-kdc.in
@@ -332,18 +332,14 @@ echo notfoo > ${objdir}/notfoopassword
 
 echo Starting kdc ; > messages.log
 env MallocStackLogging=1 MallocStackLoggingNoCompact=1 MallocErrorAbort=1 MallocLogFile=${objdir}/malloc-log \
-${kdc} &
-kdcpid=$!
-
-sh ${wait_kdc}
-if [ "$?" != 0 ] ; then
-    kill -9 ${kdcpid}
-    exit 1
-fi
+${kdc} --detach --testing ||
+    { echo "kdc failed to start"; exit 1; }
+kdcpid=`getpid kdc`
 
 echo Starting kpasswdd; > messages.log
-env ${HEIM_MALLOC_DEBUG} ${kpasswdd} &
-kpasswddpid=$!
+env ${HEIM_MALLOC_DEBUG} ${kpasswdd} --detach ||
+    { echo "kpasswdd failed to start"; exit 1; }
+kpasswddpid=`getpid kpasswdd`
 
 
 trap "kill -9 ${kdcpid} ${kpasswddpid}; echo signal killing kdc kpasswdd; exit 1;" EXIT
diff --git a/tests/kdc/check-kinit.in b/tests/kdc/check-kinit.in
--- a/tests/kdc/check-kinit.in
+++ b/tests/kdc/check-kinit.in
@@ -107,14 +107,8 @@ if (($# == 0)); then
     echo foo > ${objdir}/foopassword
 
     echo Starting kdc ; > messages.log
-    ${kdc} &
-    kdcpid=$!
-
-    sh ${wait_kdc}
-    if [ "$?" != 0 ] ; then
-	kill -9 ${kdcpid}
-	exit 1
-    fi
+    ${kdc} --detach --testing || { echo "kdc failed to start"; exit 1; }
+    kdcpid=`getpid kdc`
 
     trap "kill -9 ${kdcpid}; echo signal killing kdc; exit 1;" EXIT
 
