This commit was manufactured by cvs2svn to create tag 'heimdal-0-6-1'.
git-svn-id: svn://svn.h5l.se/heimdal/tags/heimdal-release/heimdal-0-6-1@13669 ec53bebd-3082-4978-b11e-865c3cabbd6b

diff --git a/fix-export b/fix-export
--- a/fix-export
+++ b/fix-export
@@ -13,6 +13,12 @@ if test "$DATEDVERSION"; then
 w
 q
 END
+
+	error=WARN
+	exitcmd=:
+else
+    	error=ERROR
+	exitcmd=exit
 fi
 
 ver=`sed -n 's/AC_INIT([^,]*,\([^,]*\),.*/\1/p' configure.in`
@@ -42,6 +48,12 @@ find . -name Makefile.am | while read f; do
 		y=`dirname $f`/`echo $i | sed 's/[0-9]$/cat&/'`
 		echo `grog -Tascii $x` \> $y
 		`grog -Tascii $x` > $y
+		perl -p -e 'exit 1 if (/NetBSD|FreeBSD|OpenBSD|Linux|OSF|Solaris/); exit 0;' $y
+		if [ $? != 0 ] ; then
+		    echo "$error: catfile $y contains operating system"
+		    head -1 $y
+		    $exitcmd
+		fi
 	done
 done
 
