This commit was manufactured by cvs2svn to create tag 'heimdal-0-6-6'.
git-svn-id: svn://svn.h5l.se/heimdal/tags/heimdal-release/heimdal-0-6-6@16722 ec53bebd-3082-4978-b11e-865c3cabbd6b

diff --git a/fix-export b/fix-export
--- a/fix-export
+++ b/fix-export
@@ -7,12 +7,17 @@ test -d "$1" || { echo not a dir in \$1 ; exit 1 ; }
 cd $1
 
 if test "$DATEDVERSION"; then
-	date=`date -u +%Y%m%d`
 	ed -s configure.in << END
-/AC_INIT/s/AC_INIT(\([^,]*\), [^,]*, \(.*\))/AC_INIT(\1, $date, \2)/
+/AC_INIT/s/AC_INIT(\([^,]*\), [^,]*, \(.*\))/AC_INIT(\1, $DATEDVERSION, \2)/
 w
 q
 END
+
+	error=WARN
+	exitcmd=:
+else
+    	error=ERROR
+	exitcmd=exit
 fi
 
 ver=`sed -n 's/AC_INIT([^,]*,\([^,]*\),.*/\1/p' configure.in`
@@ -42,6 +47,12 @@ find . -name Makefile.am | while read f; do
 		y=`dirname $f`/`echo $i | sed 's/[0-9]$/cat&/'`
 		echo `grog -Tascii $x` \> $y
 		`grog -Tascii $x` > $y
+		perl -p -e 'exit 1 if (/NetBSD|FreeBSD|OpenBSD|Linux|OSF|Solaris/); exit 0;' $y
+		if [ $? != 0 ] ; then
+		    echo "$error: catfile $y contains operating system"
+		    head -1 $y
+		    $exitcmd
+		fi
 	done
 done
 
@@ -49,7 +60,7 @@ make_proto () {
 	(top=`pwd`
 	cd $1
 	b=`basename $1`
-	perl $top/cf/make-proto.pl -o $2 -p $3 `(sed 's/^include/##include/' Makefile.am; 
+	perl $top/cf/make-proto.pl -o $2 -p $3 `(perl -p -e 's/^(include|if|else|endif)\b/##$1/' Makefile.am; 
 		echo 'print-sources:; @if test "$(proto_opts)"; then echo $(proto_opts); else echo -q -P comment; fi; echo '$4 | sort -u ) | make -f - print-sources `)
 }
 
