log failures

diff --git a/lib/hcrypto/test_crypto.in b/lib/hcrypto/test_crypto.in
--- a/lib/hcrypto/test_crypto.in
+++ b/lib/hcrypto/test_crypto.in
@@ -54,14 +54,16 @@ for a in unix fortuna egd ;do
 	${rand} --method=${a} --file=crypto-test 2>error
 	res=$?
 	if test "X$res" != X0 ; then
-	    grep "random not ready yet" error || exit 1
+	    grep "random not ready yet" error || \
+		{ echo "random ready failing" ; cat error; exit 1; }
 	    echo "random method $a out for lunch"
 	    continue
 	fi
 	${rand} --method=${a} --file=crypto-test2 2>error
 	res=$?
 	if test "X$res" != X0 ; then
-	    grep "random not ready yet" error || exit 1
+	    grep "random not ready yet" error || \
+		{ echo "random ready failing" ; cat error; exit 1; }
 	    echo "random metod $a out for dinner"
 	    continue
 	fi
