log the source too

diff --git a/lib/hcrypto/test_crypto.in b/lib/hcrypto/test_crypto.in
--- a/lib/hcrypto/test_crypto.in
+++ b/lib/hcrypto/test_crypto.in
@@ -55,7 +55,7 @@ for a in unix fortuna egd ;do
 	res=$?
 	if test "X$res" != X0 ; then
 	    grep "random not ready yet" error || \
-		{ echo "random ready failing" ; cat error; exit 1; }
+		{ echo "random $a ready failing" ; cat error; exit 1; }
 	    echo "random method $a out for lunch"
 	    continue
 	fi
@@ -63,7 +63,7 @@ for a in unix fortuna egd ;do
 	res=$?
 	if test "X$res" != X0 ; then
 	    grep "random not ready yet" error || \
-		{ echo "random ready failing" ; cat error; exit 1; }
+		{ echo "random $a ready failing" ; cat error; exit 1; }
 	    echo "random metod $a out for dinner"
 	    continue
 	fi
