kadm5: Add exec_hook built-in hook plugin
You can now have [kadmin] exec_hook = path-to-program in krb5.conf and
kadmin -l, kadmind, and httpkadmind, and any user of libkadm5srv will
end up executing that hook.

That will execute the hook program for every kadmin operation.  This is
done via a built-in exec hook plugin for the kadm5 plugin interface.

Exiting with an error during a pre-commit execution of the hook will
prevent the operation from being committed.

For password changes via kadmin, this can also be used as a separate
password quality check hook, though this hook can only stop the change
but without any explanation.

diff --git a/tests/kdc/check-kadmin.in b/tests/kdc/check-kadmin.in
--- a/tests/kdc/check-kadmin.in
+++ b/tests/kdc/check-kadmin.in
@@ -72,6 +72,8 @@ rm -f messages.log
 
 > messages.log
 
+> ${top_builddir}/kadm5_exec_hook.log
+
 echo Creating database
 ${kadmin} -l \
     init \
@@ -92,6 +94,10 @@ ${kadmin} -l cpw --keepold --random-key prune@${R} || exit 1
 ${kadmin} -l cpw --keepold --random-key prune@${R} || exit 1
 ${kadmin} -l add -p "$foopassword" --use-defaults pruneall@${R} || exit 1
 ${kadmin} -l cpw --pruneall --random-key pruneall@${R} || exit 1
+
+# We only use krb5-exec_hook.conf for a few commands to avoid making
+# check-valgrind prohibitive.
+KRB5_CONFIG="${objdir}/krb5-exec_hook.conf" \
 ${kadmin} -l cpw --pruneall --random-key pruneall@${R} || exit 1
 
 echo "$foopassword" > ${objdir}/foopassword
@@ -406,6 +412,11 @@ cat kadmin.tmp | ${EGREP} Keytypes: | cut -d: -f2 | tr ' ' '
 
 echo "killing kdc (${kdcpid} ${kadmpid})"
 sh ${leaks_kill} kdc $kdcpid || exit 1
+
+if [ `wc -l < ${top_builddir}/kadm5_exec_hook.log` -eq 0 ]; then
+    echo "exec_hook failed" 1>&2
+    ec=1
+fi
 
 trap "" EXIT
 
